eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka,http://localhost:9001/eureka,http://localhost:9002/eureka,http://localhost:9003/eureka
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
server:
  port: 9300
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
management:
  endpoint:
    configprops:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
info:
  app:
    name: gateway-server